In [42]:
import numpy as np

def trocaLinha(E, l1, l2): # l1 <-> l2
    aux = np.copy(E[l2,:])  
    E[l2,:] = np.copy(E[l1,:])  
    E[l1,:] = np.copy(aux)  
    return E

E = np.array([[0.4, 0.2857142857142857, -0.7777777777777778], 
              [-0.8888888888888888, 0.4, -0.8571428571428571],
              [-0.7142857142857143, 0.3333333333333333, 1.125]], dtype='double')  
print(E)  




[[ 0.4         0.28571429 -0.77777778]
 [-0.88888889  0.4        -0.85714286]
 [-0.71428571  0.33333333  1.125     ]]


In [43]:
E = trocaLinha(E, 0, 1)
E

array([[-0.88888889,  0.4       , -0.85714286],
       [ 0.4       ,  0.28571429, -0.77777778],
       [-0.71428571,  0.33333333,  1.125     ]])

In [44]:
E[1, :] = (7/5.0) * E[2, :] + E[1, :]
E

array([[-0.88888889,  0.4       , -0.85714286],
       [-0.6       ,  0.75238095,  0.79722222],
       [-0.71428571,  0.33333333,  1.125     ]])

In [45]:
E[2, :] *= (-5/ 8.0)
E

array([[-0.88888889,  0.4       , -0.85714286],
       [-0.6       ,  0.75238095,  0.79722222],
       [ 0.44642857, -0.20833333, -0.703125  ]])

In [46]:
E = trocaLinha(E, 1, 2)
E

array([[-0.88888889,  0.4       , -0.85714286],
       [ 0.44642857, -0.20833333, -0.703125  ],
       [-0.6       ,  0.75238095,  0.79722222]])

In [54]:
E.view()

array([[-0.88888889,  0.4       , -0.85714286],
       [ 0.44642857, -0.20833333, -0.703125  ],
       [-0.6       ,  0.75238095,  0.79722222]])